# Generated by Django 3.0.3 on 2020-03-22 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название проекта')),
                ('location', models.CharField(max_length=100, verbose_name='Адрес')),
                ('name_of_customer', models.CharField(max_length=100, verbose_name='Имя заказчика')),
                ('email_of_customer', models.EmailField(max_length=100, verbose_name='Почта заказчика')),
                ('number_of_customer', models.CharField(max_length=100, verbose_name='Номер заказчика')),
                ('price_of_project', models.IntegerField(verbose_name='Цена проекта')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=20, verbose_name='Фамиля')),
                ('number', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=50, verbose_name='Почта')),
                ('quantity_of_workers', models.IntegerField(default=0, verbose_name='Количество работников')),
                ('job', models.CharField(choices=[('Исполнитель', 'Исполнитель')], max_length=20, verbose_name='Профессия')),
                ('city', models.CharField(blank=True, max_length=30, verbose_name='Город')),
                ('login', models.CharField(max_length=50, verbose_name='Логин')),
                ('passwd', models.CharField(max_length=100, verbose_name='Пароль')),
            ],
        ),
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(max_length=10)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='designer.Project', verbose_name='Проект')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='designer.User', verbose_name='Исполнитель'),
        ),
    ]
