# Generated by Django 2.2.7 on 2020-05-05 12:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название проекта')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(choices=[('Зал', 'Зал'), ('Гостинная', 'Гостинная'), ('Прихожая', 'Прихожая'), ('Ванная', 'Ванная'), ('Санузел', 'Санузел'), ('Гостевой санузел', 'Гостевой санузел'), ('Гостеванная ванная', 'Гостеванная ванная'), ('Главная ванная', 'Главная ванная'), ('Гардероб', 'Гардероб'), ('Спальня', 'Спальня'), ('Главная спальня', 'Главная спальня'), ('Детская', 'Детская'), ('Балкон', 'Балкон'), ('Лоджия', 'Лоджия'), ('Кабинет', 'Кабинет'), ('Кухня', 'Кухня'), ('Летняя кухня', 'Летняя кухня'), ('Котельная', 'Котельная'), ('Хозяйственной помещение', 'Хозяйственной помещение'), ('Прачечная', 'Прачечная')], default='', max_length=25, verbose_name='Название комнаты')),
                ('images', models.ImageField(blank=True, default='', upload_to='statement/photos', verbose_name='Фото')),
                ('product_name', models.CharField(blank=True, default='', max_length=250, verbose_name='Имя продукта')),
                ('link', models.URLField(blank=True, default='', max_length=100, verbose_name='Ссылка на товар')),
                ('unit', models.CharField(blank=True, default='', max_length=100, verbose_name='Единица измерения')),
                ('retail_price', models.IntegerField(default=0, verbose_name='Цена постащика(БЕЗ СКИДКИ!)')),
                ('qty', models.IntegerField(default=0, verbose_name='Количество')),
                ('total_client_price', models.IntegerField(default=0, verbose_name='Общая сумма позиции')),
                ('file_3dmax', models.FileField(blank=True, default='', upload_to='statement/files')),
                ('file_revit', models.FileField(blank=True, default='', upload_to='statement/files')),
                ('file_technical_instruction', models.FileField(blank=True, default='', upload_to='statement/files')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='designer.Project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Ведомость',
                'verbose_name_plural': 'Ведомости',
            },
        ),
    ]
