# Generated by Django 3.0.3 on 2020-03-24 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designer', '0002_auto_20200322_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='statement',
            name='application_room',
            field=models.CharField(choices=[('Все комнаты', 'Все комнаты'), ('Зал', 'Зал'), ('Гостинная', 'Гостинная'), ('Прихожая', 'Прихожая'), ('Ванная', 'Ванная'), ('Санузел', 'Санузел'), ('Гостевой санузел', 'Гостевой санузел'), ('Гостеванная ванная', 'Гостеванная ванная'), ('Главная ванная', 'Главная ванная'), ('Гардероб', 'Гардероб'), ('Спальня', 'Спальня'), ('Главная спальня', 'Главная спальня'), ('Детская', 'Детская'), ('Балкон', 'Балкон'), ('Лоджия', 'Лоджия'), ('Кабинет', 'Кабинет'), ('Кухня', 'Кухня'), ('Летняя кухня', 'Летняя кухня'), ('Котельная', 'Котельная'), ('Хозяйственной помещение', 'Хозяйственной помещение'), ('Прачечная', 'Прачечная')], default='', max_length=25, verbose_name='Тип продукта'),
        ),
        migrations.AddField(
            model_name='statement',
            name='aviability_of_stock',
            field=models.CharField(choices=[('На складе', 'На складе'), ('Под заказ', 'Под заказ'), ('Ожидается поступление', 'Ожидается поступление')], default='', max_length=25),
        ),
        migrations.AddField(
            model_name='statement',
            name='client_approved',
            field=models.CharField(choices=[('Да', 'Да'), ('Нет', 'Нет')], default='', max_length=3),
        ),
        migrations.AddField(
            model_name='statement',
            name='client_discount',
            field=models.IntegerField(default=0, verbose_name='Скидка для клиента'),
        ),
        migrations.AddField(
            model_name='statement',
            name='designer_discount',
            field=models.IntegerField(default=0, verbose_name='Скидка для дизайнера'),
        ),
        migrations.AddField(
            model_name='statement',
            name='file_3dmax',
            field=models.FileField(blank=True, default='', upload_to='statement/files'),
        ),
        migrations.AddField(
            model_name='statement',
            name='file_revit',
            field=models.FileField(blank=True, default='', upload_to='statement/files'),
        ),
        migrations.AddField(
            model_name='statement',
            name='file_technical_instruction',
            field=models.FileField(blank=True, default='', upload_to='statement/files'),
        ),
        migrations.AddField(
            model_name='statement',
            name='images',
            field=models.ImageField(blank=True, default='', upload_to='statement/photos', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='statement',
            name='link',
            field=models.URLField(blank=True, default='', max_length=100, verbose_name='Ссылка на товар'),
        ),
        migrations.AddField(
            model_name='statement',
            name='model',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Модель/Артикул'),
        ),
        migrations.AddField(
            model_name='statement',
            name='product_name',
            field=models.CharField(blank=True, default='', max_length=250, verbose_name='Имя продукта'),
        ),
        migrations.AddField(
            model_name='statement',
            name='product_type',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Тип продукта'),
        ),
        migrations.AddField(
            model_name='statement',
            name='qty',
            field=models.IntegerField(default=0, verbose_name='Количество'),
        ),
        migrations.AddField(
            model_name='statement',
            name='retail_price',
            field=models.IntegerField(default=0, verbose_name='Цена постащика(БЕЗ СКИДКИ!)'),
        ),
        migrations.AddField(
            model_name='statement',
            name='supplier',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='statement',
            name='total_client_price',
            field=models.IntegerField(default=0, verbose_name='Общая сумма позиции'),
        ),
        migrations.AlterField(
            model_name='statement',
            name='room',
            field=models.CharField(choices=[('Зал', 'Зал'), ('Гостинная', 'Гостинная'), ('Прихожая', 'Прихожая'), ('Ванная', 'Ванная'), ('Санузел', 'Санузел'), ('Гостевой санузел', 'Гостевой санузел'), ('Гостеванная ванная', 'Гостеванная ванная'), ('Главная ванная', 'Главная ванная'), ('Гардероб', 'Гардероб'), ('Спальня', 'Спальня'), ('Главная спальня', 'Главная спальня'), ('Детская', 'Детская'), ('Балкон', 'Балкон'), ('Лоджия', 'Лоджия'), ('Кабинет', 'Кабинет'), ('Кухня', 'Кухня'), ('Летняя кухня', 'Летняя кухня'), ('Котельная', 'Котельная'), ('Хозяйственной помещение', 'Хозяйственной помещение'), ('Прачечная', 'Прачечная')], default='', max_length=25, verbose_name='Название комнаты'),
        ),
    ]
